remote_theme: "mmistakes/minimal-mistakes@4.17.2"

locale: "en-US"
title                    : "Blitz.Dev"
title_separator          : "-"
subtitle                 : "Patrick Blitz"
name                     : &name "Patrick Blitz" # &name is a YAML anchor which can be *referenced later
description              : &description "."
url                      : https://blitz.dev # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/" # the subpath of your site, e.g. "/blog"
repository               : "mmistakes/minimal-mistakes"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
words_per_minute         : 200

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

twitter:
  username               : &twitter "lordthundering"

#social:
#  type                   : # Person or Organization (defaults to Person)
#  name                   : # If the user or organization name differs from the site's name
#  links: # An array of links to social media profiles
#    - "https://twitter.com/lordthundering"
#    - "https://www.linkedin.com/in/pblitz/"

author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/images/blitz.jpg"
  bio              : "Developer, IoT Enthusiast, Father. Not necessarly in that order"
  location         : "Munich"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/lordthundering"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pblitz"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/pblitz/"


# Build settings
#theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate

#year_archive:
#  type: liquid
#  path: /year-archive/

include:
  - .htaccess
  - _pages
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true